# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: gl:openscm/copier-basic-python-repository
email: hoegner@iiasa.ac.at
name: Annika Hoegner
notebooks: true
package_manager: uv
project_description_short: basic copier scratch repo
project_url: https://github.com/eahoegner/matplotlib_scratch
